# Generated by Django 3.2 on 2023-08-14 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Gas Leak', 'Gas Leak'), ('Meter Installation', 'Meter Installation'), ('Billing Inquiry', 'Billing Inquiry')], max_length=50)),
                ('details', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('In Process', 'In Process'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('submission_timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolution_timestamp', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
